# turn off status bar
set -g status off

# neovim stuff
# fix terminal colors
set-option -g default-terminal "screen-256color"
set-option -a terminal-features 'xterm-kitty:RGB'
# fix excape time
set-option -sg escape-time 10
# fix autofocus
set-option -g focus-events on
